"""add_terms_accepted_to_users

Revision ID: d28e55713037
Revises: add_email_auth_001
Create Date: 2026-01-30 05:16:23.824083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28e55713037'
down_revision: Union[str, None] = 'add_email_auth_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('terms_accepted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'terms_accepted_at')
    op.drop_column('users', 'terms_accepted')
    # ### end Alembic commands ###
